# DEAI-opdrachten Lineaire Regressie

### 2. Inlezen

In [68]:
import pandas as pd
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler

In [69]:
df = pd.read_excel("AmesHousing.xlsx", sheet_name="AmesHousing")

# check
df.head()

# Laat de colom naamen zien
df.columns

Index(['ID', 'SalePrice', 'Garage', 'Overall Qual', 'Gr Liv Area',
       'Total Bsmt SF', 'Lot Area', 'Year Built', 'Full Bath', 'Bedroom AbvGr',
       'Neighborhood', 'House Style'],
      dtype='str')

### 3. features en target

In [73]:
# Check of ze egt bestaan
df[["Gr Liv Area", "Overall Qual", "Neighborhood"]].head()
df[["Gr Liv Area", "Overall Qual", "Year Built", "Total Bsmt SF", "Neighborhood"]].head()

   Gr Liv Area  Overall Qual  Year Built  Total Bsmt SF Neighborhood
0         1656             6        1960         1080.0        NAmes
1          896             5        1961          882.0        NAmes
2         1329             6        1958         1329.0        NAmes
3         2110             7        1968         2110.0        NAmes
4         1629             5        1997          928.0      Gilbert

### 4.A One-hot

In [74]:
# Zet tekst om in true en false zodat er mee gerekend kan worden
df_encoded = pd.get_dummies(df, columns=["Neighborhood"])

df_encoded.head()

,ID,SalePrice,Garage,Overall Qual,Gr Liv Area,Total Bsmt SF,Lot Area,Year Built,Full Bath,Bedroom AbvGr,...,Neighborhood_NoRidge,Neighborhood_NridgHt,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker
0,1,215000,yes,6,1656,1080.0,31770,1960,1,3,...,False,False,False,False,False,False,False,False,False,False
1,2,105000,yes,5,896,882.0,11622,1961,1,2,...,False,False,False,False,False,False,False,False,False,False
2,3,172000,yes,6,1329,1329.0,14267,1958,1,3,...,False,False,False,False,False,False,False,False,False,False
3,4,244000,yes,7,2110,2110.0,11160,1968,2,3,...,False,False,False,False,False,False,False,False,False,False
4,5,189900,yes,5,1629,928.0,13830,1997,2,3,...,False,False,False,False,False,False,False,False,False,False

### 4.B Split horizontaal en verticaal

In [84]:
# X = wat je gebruikt om te voorspelen
# col for col in .... pakt alle kolommen van Neighborhood die uit de one_hot kwamen
# De onderste code woort voor test 1, 2 en 3 gebruikt
# X = df_encoded[["Gr Liv Area", "Overall Qual"] + [col for col in df_encoded.columns if "Neighborhood_" in col]]

# deze woort gebruikt voor test 4
X = df_encoded[
    ["Gr Liv Area", "Overall Qual", "Year Built"] +
    [col for col in df_encoded.columns if "Neighborhood_" in col]
]
# Y = output
y = df_encoded["SalePrice"]

### Dataset Splitsen

In [85]:
# train set = model leren & Test set = eerlijk testen
# Anders leert de model alleen maar uit zijn hoofd
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Dit is voor de nieuwe maarnier en zorg dat R2 niet zeer laag staan (het lost dat probleem dus op)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### 5. Model maken en trainen

In [86]:
# zo had ik het eerst:
# fit_intercept=True = model begint niet bij 0 
# # positive=False = gewichten mogen negatief zijn 
# test 1: model = LinearRegression(fit_intercept=True, positive=False) 

# aangepast:
# SGDRegressor() = leert stap voor stap
# max_iter = epochs
# eta0 = Learning rate
# test 2: model = SGDRegressor(max_iter=1000, eta0=0.01, random_state=42)
# de ondeste code woord voor test 3 en 4 gebruikt
model = SGDRegressor(max_iter=2000, eta0=0.001, random_state=42)
model.fit(X_train, y_train)

SGDRegressor(eta0=0.001, max_iter=2000, random_state=42)

### 6. Evalueren

In [87]:
y_pred = model.predict(X_test)

# MSE = meet hoe fout de model zit
mse = mean_squared_error(y_test, y_pred)
# r2 = hoe goed de model de data uitlegt
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2:", r2)

MSE: 1497106037.8897483
R2: 0.8132713329821972

### 7. Slim experimenteren
Zie logboek